<?php

$kenyaLocations = [
    'Baringo' => [
        'Baringo Central',
        'Baringo North',
        'Baringo South',
        'Eldama Ravine',
        'Mogotio',
        'Tiaty',
    ],
    'Bomet' => [
        'Bomet Central',
        'Bomet East',
        'Chepalungu',
        'Konoin',
        'Sotik',
    ],
    'Bungoma' => [
        'Bumula',
        'Kabuchai',
        'Kanduyi',
        'Kimilili',
        'Mt Elgon',
        'Sirisia',
        'Tongaren',
        'Webuye East',
        'Webuye West',
    ],
    'Busia' => [
        'Budalangi',
        'Butula',
        'Funyula',
        'Nambale',
        'Teso North',
        'Teso South',
    ],
    'Elgeyo-Marakwet' => [
        'Keiyo North',
        'Keiyo South',
        'Marakwet East',
        'Marakwet West',
    ],
    'Embu' => [
        'Manyatta',
        'Mbeere North',
        'Mbeere South',
        'Runyenjes',
    ],
    'Garissa' => [
        'Daadab',
        'Fafi',
        'Garissa Township',
        'Hulugho',
        'Ijara',
        'Lagdera',
        'Balambala',
    ],
    'Homa Bay' => [
        'Homa Bay Town',
        'Kabondo',
        'Karachwonyo',
        'Kasipul',
        'Mbita',
        'Ndhiwa',
        'Rangwe',
        'Suba',
    ],
    'Isiolo' => [
        'Isiolo',
        'Merti',
        'Garbatulla',
    ],
    'Kajiado' => [
        'Isinya',
        'Kajiado Central',
        'Kajiado North',
        'Loitokitok',
        'Mashuuru',
    ],
    'Kakamega' => [
        'Butere',
        'Kakamega Central',
        'Kakamega East',
        'Kakamega North',
        'Kakamega South',
        'Khwisero',
        'Lugari',
        'Lukuyani',
        'Lurambi',
        'Matete',
        'Mumias',
        'Mutungu',
        'Navakholo',
    ],
    'Kericho' => [
        'Ainamoi',
        'Belgut',
        'Bureti',
        'Kipkelion East',
        'Kipkelion West',
        'Soin/Sigowet',
    ],
    'Kiambu' => [
        'Gatundu North',
        'Gatundu South',
        'Githunguri',
        'Juja',
        'Kabete',
        'Kiambaa',
        'Kiambu',
        'Kikuyu',
        'Limuru',
        'Ruiru',
        'Thika Town',
        'Lari',
    ],
    'Kilifi' => [
        'Ganze',
        'Kaloleni',
        'Kilifi North',
        'Kilifi South',
        'Magarini',
        'Malindi',
        'Rabai',
    ],
    'Kirinyaga' => [
        'Kirinyaga Central',
        'Kirinyaga East',
        'Kirinyaga West',
        'Mwea East',
        'Mwea West',
    ],
    'Kisii' => [
        'Bonchari',
        'Bomachoge Borabu',
        'Bomachoge Chache',
        'Kitutu Chache North',
        'Kitutu Chache South',
        'Nyaribari Chache',
        'Nyaribari Masaba',
        'South Mugirango',
    ],
    'Kisumu' => [
        'Kisumu Central',
        'Kisumu East',
        'Kisumu West',
        'Muhoroni',
        'Nyakach',
        'Nyando',
        'Seme',
    ],
    'Kitui' => [
        'Kitui West',
        'Kitui Central',
        'Kitui Rural',
        'Kitui South',
        'Kitui East',
        'Mwingi North',
        'Mwingi West',
        'Mwingi Central',
    ],
    'Kwale' => [
        'Kinango',
        'Lunga Lunga',
        'Msambweni',
        'Matuga',
    ],
    'Laikipia' => [
        'Laikipia Central',
        'Laikipia East',
        'Laikipia North',
        'Laikipia West',
        'Nyahururu',
    ],
    'Lamu' => [
        'Lamu East',
        'Lamu West',
    ],
    'Machakos' => [
        'Kathiani',
        'Machakos Town',
        'Masinga',
        'Matungulu',
        'Mavoko',
        'Mwala',
        'Yatta',
    ],
    'Makueni' => [
        'Kaiti',
        'Kibwezi West',
        'Kibwezi East',
        'Kilome',
        'Makueni',
        'Mbooni',
    ],
    'Mandera' => [
        'Banissa',
        'Lafey',
        'Mandera East',
        'Mandera North',
        'Mandera South',
        'Mandera West',
    ],
    'Marsabit' => [
        'Laisamis',
        'Moyale',
        'North Horr',
        'Saku',
    ],
    'Meru' => [
        'Buuri',
        'Igembe Central',
        'Igembe North',
        'Igembe South',
        'Imenti Central',
        'Imenti North',
        'Imenti South',
        'Tigania East',
        'Tigania West',
    ],
    'Migori' => [
        'Awendo',
        'Kuria East',
        'Kuria West',
        'Mabera',
        'Ntimaru',
        'Rongo',
        'Suna East',
        'Suna West',
        'Uriri',
    ],
    'Mombasa' => [
        'Changamwe',
        'Jomvu',
        'Kisauni',
        'Likoni',
        'Mvita',
        'Nyali',
    ],
    'Murang\'a' => [
        'Gatanga',
        'Kahuro',
        'Kandara',
        'Kangema',
        'Kigumo',
        'Kiharu',
        'Mathioya',
        'Murang\'a South',
    ],
    'Nairobi City' => [
        'Dagoretti North',
        'Dagoretti South',
        'Embakasi Central',
        'Embakasi East',
        'Embakasi North',
        'Embakasi South',
        'Embakasi West',
        'Kamukunji',
        'Kasarani',
        'Kibra',
        'Lang\'ata',
        'Makadara',
        'Mathare',
        'Roysambu',
        'Ruaraka',
        'Starehe',
        'Westlands',
    ],
    'Nakuru' => [
        'Bahati',
        'Gilgil',
        'Kuresoi North',
        'Kuresoi South',
        'Molo',
        'Naivasha',
        'Nakuru Town East',
        'Nakuru Town West',
        'Njoro',
        'Rongai',
        'Subukia',
    ],
    'Nandi' => [
        'Aldai',
        'Chesumei',
        'Emgwen',
        'Mosop',
        'Nandi Hills',
        'Tindiret',
    ],
    'Narok' => [
        'Narok East',
        'Narok North',
        'Narok South',
        'Narok West',
        'Transmara East',
        'Transmara West',
    ],
    'Nyamira' => [
        'Borabu',
        'Manga',
        'Masaba North',
        'Nyamira North',
        'Nyamira South',
    ],
    'Nyandarua' => [
        'Kinangop',
        'Kipipiri',
        'Ndaragwa',
        'Ol-Kalou',
        'Ol Joro Orok',
    ],
    'Nyeri' => [
        'Kieni East',
        'Kieni West',
        'Mathira East',
        'Mathira West',
        'Mukurweini',
        'Nyeri Town',
        'Othaya',
        'Tetu',
    ],
    'Samburu' => [
        'Samburu East',
        'Samburu North',
        'Samburu West',
    ],
    'Siaya' => [
        'Alego Usonga',
        'Bondo',
        'Gem',
        'Rarieda',
        'Ugenya',
        'Ugunja',
    ],
    'Taita-Taveta' => [
        'Mwatate',
        'Taveta',
        'Voi',
        'Wundanyi',
    ],
    'Tana River' => [
        'Bura',
        'Galole',
        'Garsen',
    ],
    'Tharaka-Nithi' => [
        'Tharaka North',
        'Tharaka South',
        'Chuka',
        'Igambang\'ombe',
        'Maara',
        'Chiakariga',
        'Muthambi',
    ],
    'Trans Nzoia' => [
        'Cherangany',
        'Endebess',
        'Kiminini',
        'Kwanza',
        'Saboti',
    ],
    'Turkana' => [
        'Loima',
        'Turkana Central',
        'Turkana East',
        'Turkana North',
        'Turkana South',
    ],
    'Uasin Gishu' => [
        'Ainabkoi',
        'Kapseret',
        'Kesses',
        'Moiben',
        'Soy',
        'Turbo',
    ],
    'Vihiga' => [
        'Emuhaya',
        'Hamisi',
        'Luanda',
        'Sabatia',
        'Vihiga',
    ],
    'Wajir' => [
        'Eldas',
        'Tarbaj',
        'Wajir East',
        'Wajir North',
        'Wajir South',
        'Wajir West',
    ],
    'West Pokot' => [
        'Central Pokot',
        'North Pokot',
        'Pokot South',
        'West Pokot',
    ],
];

return [
    'country_suggestions' => [
        ['name' => 'Kenya', 'iso_code' => 'KE'],
        ['name' => 'Uganda', 'iso_code' => 'UG'],
        ['name' => 'Tanzania', 'iso_code' => 'TZ'],
        ['name' => 'Rwanda', 'iso_code' => 'RW'],
        ['name' => 'Burundi', 'iso_code' => 'BI'],
        ['name' => 'South Sudan', 'iso_code' => 'SS'],
        ['name' => 'Ethiopia', 'iso_code' => 'ET'],
        ['name' => 'Somalia', 'iso_code' => 'SO'],
        ['name' => 'Democratic Republic of the Congo', 'iso_code' => 'CD'],
        ['name' => 'Nigeria', 'iso_code' => 'NG'],
        ['name' => 'Ghana', 'iso_code' => 'GH'],
        ['name' => 'South Africa', 'iso_code' => 'ZA'],
        ['name' => 'Egypt', 'iso_code' => 'EG'],
        ['name' => 'Morocco', 'iso_code' => 'MA'],
        ['name' => 'Algeria', 'iso_code' => 'DZ'],
        ['name' => 'Tunisia', 'iso_code' => 'TN'],
        ['name' => 'Zambia', 'iso_code' => 'ZM'],
        ['name' => 'Zimbabwe', 'iso_code' => 'ZW'],
        ['name' => 'Malawi', 'iso_code' => 'MW'],
        ['name' => 'Mozambique', 'iso_code' => 'MZ'],
        ['name' => 'India', 'iso_code' => 'IN'],
        ['name' => 'Pakistan', 'iso_code' => 'PK'],
        ['name' => 'China', 'iso_code' => 'CN'],
        ['name' => 'Japan', 'iso_code' => 'JP'],
        ['name' => 'South Korea', 'iso_code' => 'KR'],
        ['name' => 'United Arab Emirates', 'iso_code' => 'AE'],
        ['name' => 'Saudi Arabia', 'iso_code' => 'SA'],
        ['name' => 'Qatar', 'iso_code' => 'QA'],
        ['name' => 'Turkey', 'iso_code' => 'TR'],
        ['name' => 'United Kingdom', 'iso_code' => 'GB'],
        ['name' => 'Ireland', 'iso_code' => 'IE'],
        ['name' => 'France', 'iso_code' => 'FR'],
        ['name' => 'Germany', 'iso_code' => 'DE'],
        ['name' => 'Italy', 'iso_code' => 'IT'],
        ['name' => 'Netherlands', 'iso_code' => 'NL'],
        ['name' => 'Spain', 'iso_code' => 'ES'],
        ['name' => 'Sweden', 'iso_code' => 'SE'],
        ['name' => 'Norway', 'iso_code' => 'NO'],
        ['name' => 'Canada', 'iso_code' => 'CA'],
        ['name' => 'United States', 'iso_code' => 'US'],
        ['name' => 'Mexico', 'iso_code' => 'MX'],
        ['name' => 'Brazil', 'iso_code' => 'BR'],
        ['name' => 'Australia', 'iso_code' => 'AU'],
        ['name' => 'New Zealand', 'iso_code' => 'NZ'],
    ],
    'kenya_counties' => array_keys($kenyaLocations),
    'kenya_sub_counties' => $kenyaLocations,
];
